substitutions:
  _SERVICE_NAME: trip-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:588812d1b2070fbc99bbbdf5470cd2705a927a5cd4272fef16d37370577c3cbd
    args:
      - generate
      - --include-imports

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:26b8fc76be1fbbf478fff90fd3ea11557ee5016339bc8931180d8576cc365c5d
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:26b8fc76be1fbbf478fff90fd3ea11557ee5016339bc8931180d8576cc365c5d
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:aa40df0e34b5c3e430261b346be23097b284b3027dd731a8af9b38081a7e0edb
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL,NOTIFICATION_SERVICE_URL=$_NOTIFICATION_SERVICE_URL,LOG_DEBUG=$_LOG_DEBUG
      - --set-secrets=OTP_SECRET=$_OTP_SECRET_ID:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
