substitutions:
  _SERVICE_NAME: trip-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:65bd496a89c762ad7151ca9e7d885a45dacb3671a8e8ec39738b9f844d3405ea
    args:
      - generate
      - --include-imports

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:3d00b6c1a9b862621c30fc74d4f2abfc62bcbdee631ed3febd31e7edbdf6252c
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:3d00b6c1a9b862621c30fc74d4f2abfc62bcbdee631ed3febd31e7edbdf6252c
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:2e480d7977829f1534665da1fffd98170f5345d0a6322b369b0fe08a932ce574
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL,NOTIFICATION_SERVICE_URL=$_NOTIFICATION_SERVICE_URL,LOG_DEBUG=$_LOG_DEBUG
      - --set-secrets=OTP_SECRET=$_OTP_SECRET_ID:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
