substitutions:
  _SERVICE_NAME: trip-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:6e5b0946e9ad260c9b0a2908148d081834bca26897a924d177e5e5a31eb65b33
    args:
      - generate
      - --include-imports

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:4ca6cd61ccef9c1ebcecac4e714af04557dc62f66b024887e7dbcd8fce99da6d
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:4ca6cd61ccef9c1ebcecac4e714af04557dc62f66b024887e7dbcd8fce99da6d
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:246f1d97dd5a73dbdecb547a75e8c552403c926762e2044df2f833b44d1fc9c1
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL,NOTIFICATION_SERVICE_URL=$_NOTIFICATION_SERVICE_URL,LOG_DEBUG=$_LOG_DEBUG
      - --set-secrets=OTP_SECRET=$_OTP_SECRET_ID:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
