name: Nightly

on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:

jobs:
  trunk-check:
    timeout-minutes: 10
    name: Trunk Check Upload
    runs-on: ubuntu-latest
    env:
      BUF_USER: debkanchan

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1.30.1
        with:
          github_token: ${{ github.token }}

      - name: Authenticate buf
        run: echo ${{ secrets.BUF_TOKEN }} | buf registry login --username ${{ env.BUF_USER }} --token-stdin

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Trunk Check
        uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
