name: Nightly

on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:

jobs:
  trunk-check:
    timeout-minutes: 10
    name: Trunk Check Upload
    runs-on: ubuntu-latest
    env:
      BUF_USER: debkanchan

    steps:
      - name: Checkout Code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - uses: bufbuild/buf-setup-action@480a0ee8a588045b52a847b48138c6f377a89519 # v1.31.0
        with:
          github_token: ${{ github.token }}

      - name: Authenticate buf
        run: echo ${{ secrets.BUF_TOKEN }} | buf registry login --username ${{ env.BUF_USER }} --token-stdin

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Trunk Check
        uses: trunk-io/trunk-action@da67635060feab46c164bc130690e61864a5d13b # v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
