name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

env:
  SERVICE_NAME: trip-service

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Lint
        uses: trunk-io/trunk-action@v1

      # - name: Test
      #   run: npm test:integration
