name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

permissions: read-all

env:
  SERVICE_NAME: trip-service

jobs:
  lint:
    timeout-minutes: 10
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - uses: bufbuild/buf-setup-action@bdb594084c95f0638c76c891ccb75bf4b75ef61c # v1.36.0
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Lint
        uses: trunk-io/trunk-action@86b68ffae610a05105e90b1f52ad8c549ef482c2 # v1

      # - name: Test
      #   run: npm test:integration
  auto_merge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto Merge PR if bot
    uses: dragonfish-tech/workflows/.github/workflows/auto-merge.yaml@main
