name: pr

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: trip-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: |
            node-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install Packages
        run: npm install

      - name: Lint
        uses: trunk-io/trunk-action@v1

      # - name: Format
      #   run: npm run format

      - name: Test
        run: npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ride-app/${{ env.SERVICE_NAME }}:latest
