name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

permissions: read-all

env:
  SERVICE_NAME: trip-service

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - uses: bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa # v1.28.1
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Lint
        uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1

      # - name: Test
      #   run: npm test:integration
