name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

permissions: read-all

env:
  SERVICE_NAME: trip-service

jobs:
  lint:
    timeout-minutes: 10
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1.30.1
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Lint
        uses: trunk-io/trunk-action@da67635060feab46c164bc130690e61864a5d13b # v1

      # - name: Test
      #   run: npm test:integration
  auto_merge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto Merge PR if bot
    uses: dragonfish-tech/workflows/.github/workflows/auto-merge.yaml@main
